language: node_js
node_js:
  - 6.5
  - 6.11
after_script:
  - npm run coveralls
before_install:
  - openssl aes-256-cbc -K $encrypted_17640b3d960a_key -iv
    $encrypted_17640b3d960a_iv -in .coveralls.yml.enc -out .coveralls.yml -d
