#!/bin/bash
if [[ ! -e crypto-js ]]; then
	mkdir crypto-js
fi

function get() {
	echo Getting $1...
	curl -s http://crypto-js.googlecode.com/svn/tags/3.0/build/rollups/$1.js > crypto-js/$1.js

	echo Patching $1...
	echo "/* Patch for require() */ if (typeof module != 'undefined') module.exports = CryptoJS;" >> crypto-js/$1.js
}

get hmac-sha512
